<style>
   .h4-about h4 {
        padding-left: 0px;
        font-weight: bold;
        color: #d91d15;
    }

    ul {
        padding-left: 0px;
    }
   .grey-contact a{
       color:  rgb(95, 95, 97)!important;
   }

</style>
<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>
<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Masz już dosyć stresów i zastojów w pracy spowodowanych awaryjnością sprzętu w Twojej firmie? Jeśli tak, to znalazłeś się we właściwym miejscu!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="full-box header-bacground-image2 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="content-box-white" id="section1">
    <div class="container" style="    min-width: 70%;">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-10 animated zoomIn h4-about" id="about" style="text-align: justify;">
                <h1 style="text-align: left; color: rgb(217, 29, 21);"> PARĘ SŁÓW O NAS </h1>
                <p><img src="../web/img/komputer.JPG" alt="OutSourcing IT" height="400" width="300"
                        style="float:left; margin: 0.4rem 1.4rem 0.4rem 0.4rem;     box-shadow: 0px 0px 35px -7px rgba(0, 0, 0, 0.75);" class="border-shadow">
                    <b style="color: #d91d15">Firma VeriCom Outsourcing IT od początku swojej działalności X</b> związana jest z branżą
                    IT. Początki naszej kariery wiążemy głównie z branżą Automotive, na której zbudowaliśmy
                    nasze doświadczenie oraz wiedzę. Wraz z rozwojem naszej firmy rozszerzyliśmy działalność
                    także o inne sektory rynku.
                </p>
                <p>Wszystkim naszym Klientom dostarczamy nowoczesne i unikalne rozwiązania IT o najwyższej
                    jakości. Wieloletnie doświadczenie, kompetencje naszego zespołu poparte licznymi
                    certyfikatami oraz sprawność, efektywność i bezpieczeństwo działania powoduje, że spełniamy
                    oczekiwania najbardziej wymagających Kontrahentów. Jesteśmy firmą otwartą na potrzeby
                    Klienta, dlatego do każdego zadania podchodzimy indywidualnie, z pasją i zaangażowaniem,
                    stale doskonaląc umiejętności oraz budując atmosferę przyjaznych relacji.
                </p>
                <p> Jesteśmy sprawdzonym, solidnym partnerem, którego najważniejszym kryterium działania jest
                    zadowolenie i korzyść naszych klientów.
                </p>
                <h4>WIZJA:</h4>
                <p>Być partnerem pierwszego wyboru dla firm instytucji potrzebujących wsparcia
                  <br>  teleinformatycznego o najwyższych standardach</p>
                <h4>MISJA:</h4>
                <p>Budować sukces naszych klientów, poprzez oferowanie wysokiej jakości usług<br> outsourcingowych
                    IT opartych na zdobytej wiedzy i wieloletnim doświadczeniu. </p>
                <h4>WARTOSCI:</h4>
                <p>
                <ul>
                    <li>Najwyższa jakość oferowanych usług</li>
                    <li>Profesjonalizm oraz nieustanne dążenie do perfekcji</li>
                    <li>Etyka i odpowiedzialność</li>
                    <li>Pasja</li>
                    <li></li>
                </ul>
                </p>
                <div class="row">

                    <div class="col-6">
                        <span>Zapraszamy! Zespół</span>
                        <div class="logo" id="logo" style=" height: 160px;
    width: 160px;"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
