<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>

<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="full-box header-bacground-image2 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="content-box-white" id="section1">
    <div class="container" style="    min-width: 70%;">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-8 animated zoomIn" id="about" style="text-align: justify;">
                <h3> Parę słów o nas </h3>
                <p><img src="../web/img/komputer.JPG" alt="OutSourcing IT" height="400" width="300"
                        style="float:left; margin: 0.4rem 1.4rem 0.4rem 0.4rem;">
                    <b>Firma VeriCom Outsourcing IT od początku swojej działalności X</b> związana jest z branżą
                    IT. Początki naszej kariery wiążemy głównie z branżą Automotive, na której zbudowaliśmy
                    nasze doświadczenie oraz wiedzę. Wraz z rozwojem naszej firmy rozszerzyliśmy działalność
                    także o inne sektory rynku.
                </p>
                <p>Wszystkim naszym Klientom dostarczamy nowoczesne i unikalne rozwiązania IT o najwyższej
                    jakości. Wieloletnie doświadczenie, kompetencje naszego zespołu poparte licznymi
                    certyfikatami oraz sprawność, efektywność i bezpieczeństwo działania powoduje, że spełniamy
                    oczekiwania najbardziej wymagających Kontrahentów. Jesteśmy firmą otwartą na potrzeby
                    Klienta, dlatego do każdego zadania podchodzimy indywidualnie, z pasją i zaangażowaniem,
                    stale doskonaląc umiejętności oraz budując atmosferę przyjaznych relacji.
                </p>
                <p> Jesteśmy sprawdzonym, solidnym partnerem, którego najważniejszym kryterium działania jest
                    zadowolenie i korzyść naszych klientów.
                </p>

                <h2>Zapewniamy usługi informatyczne dla firm w następujących miastach: (klikane guziki)</h2>
                <ul>
                    <li><a href="">- Outsourcing IT Dąbrowa Górnicza</a></li>
                    <li><a href="">- Outsourcing IT Katowice</a></li>
                    <li><a href="">- Outsourcing IT Gliwice</a></li>
                    <li><a href="">- Outsourcing IT Chorzów</a></li>
                    <li><a href=""> - Outsourcing IT Będzin</a></li>
                    <li><a href=""> - wszystkie inne miasta w promieniu do 40km od Dąbrowy Górniczej gdzie znajduje się
                            nasza siedziba.</a></li>
                </ul>


                <h4>Nasze wartości:</h4>
                <h4>Wizja:</h4>
                <p>Być partnerem pierwszego wyboru dla firm instytucji potrzebujących wsparcia
                    teleinformatycznego o najwyższych standardach</p>
                <h4>Misja:</h4>
                <p>Budować sukces naszych klientów, poprzez oferowanie wysokiej jakości usług outsourcingowych
                    IT opartych na zdobytej wiedzy i wieloletnim doświadczeniu. </p>
                <h4>Wartości:</h4>
                <p>
                <ul>
                    <li> Najwyższa jakość oferowanych usług</li>
                    <li>Profesjonalizm oraz nieustanne dążenie do perfekcji</li>
                    <li>Etyka i odpowiedzialność</li>
                    <li>Pasja</li>
                    <li></li>
                </ul>
                </p>
                <span>Zapraszamy!
                        Zespół Vericom</span>


            </div>
            <div class="col-4">
                <div class="text-box">
                    <h3> Adres </h3>
                    <p>
                        VERICOM <br> ul. Parkowa 53 /2 <br> 41-303 Dąbrowa Górnicza
                    </p>
                    <p>
                        NIP: 6292075389<br> REGON: 241660764
                    </p>
                </div>
                <div class="text-box">
                    <h3> Telefon i fax </h3>
                    <p>
                        +48 502 481 334</br>
                        +48 503 757 557
                    </p>
                </div>
                <div class="text-box">
                    <h3> E-mail </h3>
                    <p>
                        biuro@vericom.pl
                    </p>
                </div>
                <div class="text-box">
                    <h3> Facebook </h3>
                    <p>
                        facebook.com/vericom
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
