<style>.tick-ul ul {
        list-style: none;
    }

    .tick-ul ul li:before {
        color: red;
        font-weight: bolder;
        content: '✓';
        padding-right: 5px;
    }</style>

<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>

<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OUTSOURCING IT BĘDZIŃ
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--    <div class="full-box header-bacground-image2 animated fadeInSlider headers">-->
<!--        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>-->
<!--        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>-->
<!--        <div class="animation-box">-->
<!--            <div class="animated fadeInLeft animation-text-first">-->
<!--                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM-->
<!--                </div>-->
<!--            </div>-->
<!--            <div style="overflow-x: hidden;">-->
<!--                <div class="animated fadeInRight animation-text-second">-->
<!--                    <div class="animated fadeIn">-->
<!--                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla-->
<!--                        użytkowników (Helpdesk) oraz administrowania siecią-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
</header>

<div class="content-box-white" id="section1">
    <div class="container" style="    min-width: 70%;">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-8 animated zoomIn tick-ul" id="about" style="text-align: justify;">
                <h1> Będzin </h1>
            <p>
                Korzystając ze sprzętu komputerowego w firmie trzeba mieć pewność, że dostępne urządzenia będą technicznie na wysokim poziomie i korzystanie z nich będzie odbywać się bez niepotrzebnych awarii, które mogą utrudnić pracę. Jeśli jednak mimo posiadania nowoczesnego sprzętu problemy techniczne będą się pojawiać to w takiej sytuacji będzie trzeba sprawnie zareagować, by ponownie wrócić do pracy. Jeśli firma nie ma działu IT to w tej sytuacji oferta VeriCom, i usługi informatyczne dla firm w Będzinie, będzie tą propozycją która w firmie sprawdzi się doskonale. Bedzie można liczyć na szybką reakcję świetny specjalistów, którzy zajmą się usunięciem problemów technicznych związanych z danym sprzętem.
            </p>
                <h2>Profesjonalna oferta usług IT Będzin</h2>
                <p>
                    Wybierając outsourcing IT w Będzinie realizowany przez firmę VeriCom można oczekiwać profesjonalnej opieki ze strony doświadczonych specjalistów, którzy faktycznie będą w stanie kompleksowo zająć się sprzętem komputerowym z jakiego w firmie się korzysta sprawnie likwidując wszelkie potencjalne awarie takich urządzeń.
                </p>
               <?php include("city-common.phtml"); ?>
            </div>
            <div class="col-4 city border-shadow animated zoomIn" style="box-shadow: 0px 0px 35px -7px rgba(0, 0, 0, 0.75);">
            </div>
        </div>
    </div>
</div>
