<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>

<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Masz już dosyć stresów i zastojów w pracy spowodowanych awaryjnością sprzętu w Twojej firmie? Jeśli tak, to znalazłeś się we właściwym
                        miejscu!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="full-box header-bacground-image2 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="content-box-white" id="section1">
    <div class="container" style="    min-width: 70%;">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-5 col-md-10 animated zoomIn" id="about" style="padding-right: 100px;">
                <div>
                    <h1 style="text-align: left; color: rgb(217, 29, 21);">TEREN NA KTORYM DZIALAMY</h1>
                </div>
                <span style="font-size: 1.5rem; font-family: 'Roboto Condensed', sans-serif;">Zapewniamy usługi informatyczne dla firm na terenie całego Województwa śląskiego, z
                    szczególnym wskazaniem na poniższe miasta.</span>
                <ul style="margin-top: 1rem; padding-left: 0px" class="location">
                    <li><a href="dabrowagornicza"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Dąbrowa
                            Górnicza</a></li>
                    <li><a href="katowice"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Katowice</a></li>
                    <li><a href="gliwice"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Gliwice</a></li>
                    <li><a href="jaworzno"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Jaworzno</a></li>
                    <li><a href="bedzin"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Będzin</a></li>
                </ul>
            </div>
            <div class="col-7 col-md-10 animated zoomIn map border-shadow" style="    min-height: 450px;"></div>
        </div>
    </div>
</div>
