<div class="col-4 grey-contact animated zoomIn">
    <div class="text-box">
        <h3> Adres </h3>
        <p>
            VERICOM <br><a href="https://www.google.com/maps/place/Parkowa+53,+41-303+Dąbrowa+Górnicza/">ul. Parkowa 53 /2 </a> <br> 41-303 Dąbrowa Górnicza
        </p>
        <p>
            NIP: 6292075389<br> REGON: 241660764
        </p>
    </div>
    <div class="text-box">
        <h3> Telefon i fax </h3>
        <p>
            <a href="tel:+48 502 481 334">+48 502 481 334</a> </br>
            <a href="tel:+48 503 757 557">+48 503 757 557</a>
        </p>
    </div>
    <div class="text-box">
        <h3> E-mail </h3>
        <p>
            <a href="mailto:biuro@vericom.pl">biuro@vericom.pl</a>
        </p>
    </div>
    <div class="text-box">
        <h3> Facebook </h3>
        <p>
            facebook.com/vericom
        </p>
    </div>
</div>
