<style>.tick-ul ul {
        list-style: none;
    }

    .tick-ul ul li:before {
        color: red;
        font-weight: bolder;
        content: '✓';
        padding-right: 5px;
    }</style>

<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>

<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="full-box header-bacground-image2 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="content-box-white" id="section1">
    <div class="container" style="    min-width: 70%;">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-8 animated zoomIn tick-ul" id="about" style="text-align: justify;">
                <h1> Dąbrowa Górnicza </h1>
            <p>
                Prowadzenie nowoczesnej firmy w dużej mierze opiera się oczywiście na sprzęcie komputerowym jaki w takich firmach się wykorzystuje. Wszelkie problemy techniczne jakie mogą się pojawić ze sprzętem mogą powodować utrudnienia w prowadzeniu działalności albo całkowicie to uniemożliwiać. Aby takiej sytuacji uniknąć będzie trzeba mieć sprawną obsługę IT w firmie. Wybór może paść na firmę VeriCom, która oferuje usługi informatyczne dla firm w Dąbrowie Górniczej. To świetna propozycja, ponieważ nie trzeba tworzyć stałego stanowiska pracy w firmie o tym charakterze, tylko będzie można korzystać z zewnętrznej firmy, gdy taka potrzeba będzie się pojawiała.
            </p>
                <h2>Wybór profesjonalnej oferty outsourcingu IT Dąbrowa Górnicza</h2>
                <p>
                    Wybierając outosurcing IT w Dąbrowie Górniczej bez obaw można się decydować na ofertę przygotowaną przez firmę VeriCom. Duże doświadczenie w tym zakresie oraz świetne grono specjalistów znających się na sprzęcie komputerowym to gwarancja profesjonalnej realizacji usług w zakresie IT dla firm niezależnie od tego z jakim problemem będzie trzeba się zmagać.
                </p>
               <?php include("city-common.phtml"); ?>
            </div>
            <div class="col-4">
                <div class="text-box">
                    <h3> Adres </h3>
                    <p>
                        VERICOM <br> ul. Parkowa 53 /2 <br> 41-303 Dąbrowa Górnicza
                    </p>
                    <p>
                        NIP: 6292075389<br> REGON: 241660764
                    </p>
                </div>
                <div class="text-box">
                    <h3> Telefon i fax </h3>
                    <p>
                        +48 502 481 334</br>
                        +48 503 757 557
                    </p>
                </div>
                <div class="text-box">
                    <h3> E-mail </h3>
                    <p>
                        biuro@vericom.pl
                    </p>
                </div>
                <div class="text-box">
                    <h3> Facebook </h3>
                    <p>
                        facebook.com/vericom
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
