<footer id="section3">
    <div class="container">
        <div class="row container-margin">
            <div class="col">
                <h4> DANE FIRMOWE </h4>
                <p>
                    VERICOM <br> ul. Parkowa 53 /2 <br> 41-303 Dąbrowa Górnicza
                </p>
                <p>
                    NIP: 6292075389<br> REGON: 241660764
                </p>
            </div>
            <div class="col">
                <h4> KONTAKT </h4>
                <p>
                    +48 502 481 334</br>
                    +48 503 757 557
                </p>
                <p>
                    biuro@vericom.pl
                </p>
            </div>
            <div class="col">
                <h4> KONTAKT </h4>
                <p>
                    <img width="90" height="90" src="application/web/img/fb.png" alt="" style="max-width: 100%; height: auto;">
                </p>
                <p>
                    facebook.com/vericom
                </p>
            </div>
            <div class="col">
                <h4 style="margin-bottom:0px;"> RZETELNA FIRMA </h4>
                <img width="250" height="90" src="application/web/img/rzetelnafirma.png" alt=""
                     style="max-width: 100%; height: auto;">
            </div>
        </div>
    </div>
</footer>
<script src='https://www.google.com/recaptcha/api.js'></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-migrate-3.0.1.js"></script>
<script type="text/javascript" src="application/web/js/bootstrap.min.js"></script>
<script type="text/javascript" src="application/web/js/outdatedbrowser.min.js"></script>
<script type="text/javascript" src="application/web/js/scroll.js"></script>
<script type="text/javascript" src="application/web/js/animate.js"></script>
<script type="text/javascript" src="application/web/js/scripts.js"></script>
