<style>.tick-ul ul {
        list-style: none;
    }

    .tick-ul ul li:before {
        color: red;
        font-weight: bolder;
        content: '✓';
        padding-right: 5px;
    }</style>

<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>

<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OUTSOURCING IT GLIWICE
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Masz już dosyć stresów i zastojów w pracy spowodowanych awaryjnością sprzętu w Twojej firmie? Jeśli tak, to znalazłeś się we właściwym miejscu!
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--    <div class="full-box header-bacground-image2 animated fadeInSlider headers">-->
<!--        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>-->
<!--        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>-->
<!--        <div class="animation-box">-->
<!--            <div class="animated fadeInLeft animation-text-first">-->
<!--                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM-->
<!--                </div>-->
<!--            </div>-->
<!--            <div style="overflow-x: hidden;">-->
<!--                <div class="animated fadeInRight animation-text-second">-->
<!--                    <div class="animated fadeIn">-->
<!--                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla-->
<!--                        użytkowników (Helpdesk) oraz administrowania siecią-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
</header>

<div class="content-box-white" id="section1">
    <div class="container" style="    min-width: 70%;">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-8 animated zoomIn tick-ul" id="about" style="text-align: justify;">
                <h1> Gliwice </h1>
            <p>
                Problemy ze sprzętem komputerowym w firmie mogą doprowadzić do wielu różnych problemów jeśli chodzi o prowadzenie działalności. Jednak nadal chodzi tutaj o sprzęty, które ze względu na swoją naturę mogą ulegać uszkodzeniom. Dlatego każdy przedsiębiorca powinien być na tą sytuację przygotowany i mieć specjalistów, którzy będą w stanie szybko sprzęt komputerowy doprowadzić w firmie do porządku. Obecnie usługi informatyczne dla firm w Gliwicach to świetna oferta przygotowana przez firmę VeriCom, która zajmuje się kompleksową obsługą przedsiębiorców w tym zakresie gwarantując sprawną reakcję na pojawiające się problemy techniczne.
            </p>
                <h2>Zewnętrzna obsługa IT dla firm Gliwice</h2>
                <p>
                    Wydaje się, że to właśnie outsourcing IT dla firm w Gliwicach będzie najlepszym rozwiązaniem, ponieważ w takiej sytuacji oddaje się firmę w dobre ręce specjalistów, którzy będą w stanie zagwarantować sprawną obsługę wszystkich problemów związanych ze sprzętem komputerowym w firmie. Warto z takich możliwości skorzystać ponieważ będzie to kompleksowa obsługa ze, a koszty będą niższe niż tworzenie działu IT w firmie.
                </p>
               <?php include("city-common.phtml"); ?>
            </div>
            <div class="col-4 city border-shadow animated zoomIn" style="box-shadow: 0px 0px 35px -7px rgba(0, 0, 0, 0.75);">
            </div>
        </div>
    </div>
</div>
