<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VeriCom OutSourcing IT</title>
    <link href="application/web/css/reset.css" rel="stylesheet" type="text/css" media="all">
    <link href="application/web/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
    <link href="application/web/css/style.css" rel="stylesheet" type="text/css" media="all">
    <link href="application/web/css/contact.css" rel="stylesheet" type="text/css" media="all">
    <link href="application/web/css/animate.css" rel="stylesheet" type="text/css" media="all">
    <link href="application/web/css/odometer.css" rel="stylesheet" type="text/css" media="all">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
