<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>

<header class=" dotted">
    <div class=" header-bacground-help animated fadeInSlider headers">
        <div class="container" style="    min-width: 70%; margin-top: 180px">

        <h1 style="    color: #313132;
    font-size: 36px;
    line-height: 45px;
    font-weight: 600;
    letter-spacing: 0px;
    text-align: left;">Pomoc zdalna</h1>

        </div>
    </div>
</header>

<div class="content-box-white" id="section1" style="background-color: rgba(128, 128, 128, 0.05);">
    <div class="container" style="    min-width: 70%; ">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-xl-8 col-sm-10  animated zoomIn" style="margin-bottom: 100px; margin-top: -170px;
    background: white;">
                <div class="column mcb-column mcb-item-35pqqu31v one column_column" style="margin: 5%;">
                    <div class="column_attr clearfix" style="padding:0 10% 0 0;"><h2 style=" text-align: left; color :rgb(217, 29, 21);">Zdalne wsparcie</h2>
                        <p>To wygodna forma uzyskania wsparcia informatycznego, bez wychodzenia z domu i oddawania urządzenia do naprawy.</p>
                        <p>Możliwe do realizacji przez niemal 24 godziny, 7 dni w tygodniu.</p>
                        <p>Wystarczy, aby komputer miał sprawne połączenie internetowe.</p>
                        <p>Połączenie z Twoim komputerem odbędzie się przez program TeamViewer. Oprogramowanie to jest jednym z najpopularniejszych na świecie
                            rozwiązań do zdalnego wsparcia. Jego producentem jest TeamViewer GmbH (<a href="https://www.teamviewer.com/en/privacy-policy/"
                                                                                                      style="color :rgb(217, 29, 21);">
                                sprawdź politykę prywatności</a>)</p>
                        <a href="https://get.teamviewer.com/wdtvy83" class="button_help">Pobierz</a></div>
                </div>
            </div>
        </div>
    </div>
</div>

