<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>

<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="full-box header-bacground-image2 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="full-box-menu" id="full-box-menu">
        <div class="container-menu">
            <div class="hamburger" id="hamburger" onclick="myHamburger()">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </div>
            <div class="logobox">
                <div class="logo" id="logo">
                </div>
            </div>

            <div class="menu-normal" id="top-menu">
                <ul class="">
                    <li><a href="index.phtml">Home</a></li>
                    <li><a href="about.phtml">O Nas</a></li>
                    <li><a href="/">Oferta</a></li>
                    <li><a href="/">Referencje</a></li>
                    <li><a href="/">Pomoc zdalna</a></li>
                    <li><a href="/">Kontakt</a></li>
                </ul>
            </div>
        </div>
        <div id="navigation" class="menu menu-link">
            <ul class="topnav" id="myTopnav">
                <li><a href="index.phtml">Home</a></li>
                <li><a href="about.phtml">O Nas</a></li>
                <li><a href="/">Oferta</a></li>
                <li><a href="/">Referencje</a></li>
                <li><a href="/">Pomoc zdalna</a></li>
                <li><a href="/">Kontakt</a></li>
            </ul>
        </div>
    </div>
</header>

<div class="content-box-white" id="section1">
    <div class="container" style="    min-width: 70%;">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-8 animated zoomIn" id="about">
                <h3> Parę słów o nas </h3>
                <p><img src="../web/img/Logo.png" alt="OutSourcing IT" height="100" width="190"
                        style="float:left; margin:0.4rem"> już<b> od 7 lat specjalizuje się w kompleksowym wsparciu
                        informatycznym przedsiębiorstw.</b> Naszym przesłaniem jest całościowe podejście
                    do oczekiwań i zadań stawianych nam przez naszych Klientów.</p>
                <p> Zapewniamy przedsiębiorstwom pełną<b> opiekę informatyczną realizowaną w modelu outsourcingowym.</b>
                    Naszym celem jest zabezpieczenie ciągłości pracy oraz bezpieczeństwa systemów informatycznych
                    Klienta.</p>
                <p> Jako firma informatyczna świadczymy również profesjonalne wsparcie w zakresie rozwiązań systemowych
                    dla biznesu.
                    <b> Specjalizujemy się w projektowaniu i wdrażaniu systemów informatycznych na indywidualne
                        zamówienie Klienta.</b> W tym celu stworzyliśmy autorską platformę Prelude BPM®, która jest
                    niezawodnym narzędziem pozwalającym na modelowanie
                    dowolnych procesów zachodzących w organizacji.</p>
                <p> MOSPAN zajmuje się ponadto
                    <b> dostawą profesjonalnego sprzętu IT.</b> W tym celu współpracujemy z czołowymi producentami
                    komputerów, podzespołów, urządzeń peryferyjnych oraz infrastruktury sieciowej.
                    <b> Jesteśmy m.in. wyłącznym dystrybutorem na Polskę firmy ICY DOCK®</b> – renomowanego producenta
                    urządzeń pamięci masowych i archiwizacji danych. </p>
            </div>
            <div class="col-4">
                <div class="text-box">
                    <h3> Adres </h3>
                    <p>
                        VERICOM <br> ul. Parkowa 53 /2 <br> 41-303 Dąbrowa Górnicza
                    </p>
                    <p>
                        NIP: 6292075389<br> REGON: 241660764
                    </p>
                </div>
                <div class="text-box">
                    <h3> Telefon i fax </h3>
                    <p>
                        +48 502 481 334</br>
                        +48 503 757 557
                    </p>
                </div>
                <div class="text-box">
                    <h3> E-mail </h3>
                    <p>
                        biuro@vericom.pl
                    </p>
                </div>
                <div class="text-box">
                    <h3> Facebook </h3>
                    <p>
                        facebook.com/vericom
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

