<style>
    /*.owl-carousel .owl-stage {*/
    /*    display: flex;*/
    /*}*/

    .owl-carousel .owl-item img {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }

    /*.owl-carousel .owl-item {*/
    /*    width: auto;*/
    /*    display: block;*/
    /*    margin-left: auto;*/
    /*    margin-right: auto*/
    /*}*/
</style>
<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>
<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OUTSOURCING IT W TWOJEJ FIRMIE
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Masz już dosyć stresów i zastojów w pracy spowodowanych awaryjnością sprzętu w Twojej firmie?<br> Jeśli tak, to znalazłeś się we
                        właściwym
                        miejscu!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="full-box header-bacground-image2 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!--<div class="content-box-grey">-->
<!--    <div class="container">-->
<!--        <div class="row row-50 justify-content-center justify-content-lg-between container-margin">-->
<!--            <div class="col-md-12 col-lg-12 col-xs-12 animated zoomIn" id="about">-->
<!--                <img src="web/img/stres.jpg" alt="OutSourcing IT" height="350" width="430"-->
<!--                     style="float:left; margin:0.4rem">-->
<!--                <p style="    color: #d91d15;-->
<!--    font-weight: bolder;-->
<!--    letter-spacing: 0.5px;"> Masz już dosyć stresów i zastojów w pracy spowodowanych awaryjnością sprzętu w Twojej-->
<!--                    firmie?-->
<!--                    Jeśli tak, to znalazłeś się we właściwym miejscu!-->
<!--                </p>-->
<!--            </div>-->
<!---->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<div class="content-box-white" id="section1">
    <div class="container">
        <div class="row row-50 justify-content-center justify-content-lg-between container-margin">
            <div class=" col-md-6 col-lg-6 col-xs-6 animated fadeInLeft">
                <!--                <h1>OUTSOURCING IT W TWOJEJ FIRMIE</h1>-->
                <!--                <p>Masz już dosyć stresów i zastojów w pracy spowodowanych awaryjnością sprzętu w Twojej firmie?-->
                <!--                    Jeśli tak,<b> to znalazłeś się we właściwym miejscu!</b>-->
                <span style="font-size: 20px; color: rgb(217, 29, 21);"><b> Pomagamy ludziom takim jak Ty od 2010 roku </b></span>

                <!--                <img src="web/img/question.jpg" alt="OutSourcing IT" height="140" width="200"-->
                <!--                     style="float:left; margin:0.4rem 0.6rem 0rem 0rem">-->
                <p>
                <ul style="font-size: 16px; padding-left: 0px">
                    <li>- Brak internetu
                    </li>
                    <li>- Notoryczne błędy
                    </li>
                    <li>- Migający monitor
                    </li>
                    <li>- Wyłączający się komputer
                    </li>
                    <li>- Migający monitor
                    </li>
                    <li>- Nie działające kamery
                    </li>
                    <li>- Brak połączenia z serwerem
                    </li>
                </ul>
                <p style="padding-top: 10px;"><b style="color: rgb(217, 29, 21);">To tylko przykładowe sytuacje, które zdarzają się w przedsiębiorstwach każdego
                        dnia.</b>
                    Naprawa awarii pochłania zawsze dużą
                    ilość czasu, angażuje wiele osób oraz wywołuje nieraz niemałe zamieszanie. A jak wiemy czas to
                    pieniądz.

                    Dobrze być na to przygotowanym i powierzyć opiekę nad „złośliwością rzeczy martwych” specjalistom z
                    wieloletnim doświadczeniem. Jesteśmy tu dla Ciebie.
                </p>
            </div>
            <div class="col-md-6 col-lg-6 col-xs-6 office-worker img-mobile-hidden border-shadow animated fadeInRight">
            </div>
        </div>

    </div>
</div>
<div class="content-box-grey">
    <div class="container">
        <div class="row row-50 justify-content-center justify-content-lg-between container-margin">
            <div class="col-md-12 col-lg-12 col-xs-12" style="    padding-bottom: 30px;">
                <div class="hidden-to-animate">
                    <h2>
                        CZYM SIĘ ZAJMUJEMY
                    </h2>
                </div>
                <!--                <div class="under-text"> Sprawdź w jakich dziedzinach IT specjalizujemy się</div>-->
            </div>
            <div class="col what-we-do">
                <div class="icon service " style="height: 55px;width: 55px;     margin-bottom: 12%;">
                </div>
                <h1>
                    OPIEKA INFORMATYCZNA FIRM
                </h1>
                <!--                <p style="padding-top: 1.2rem;">Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem-->
                <!--                    IT, </P>-->
            </div>
            <div class="col what-we-do" style="    animation-delay: 400ms; ">
                <div class="icon cloud" style="    height: 70px;width: 70px;     margin-bottom: 7%;"></div>
                <h1>
                    USŁUGI W CHMURZE
                </h1>
                <!--                <p style="padding-top: 1.2rem;">Specjalizujemy się w projektowaniu systemów informatycznych</P>-->
            </div>
            <div class="col what-we-do" style="    animation-delay: 800ms;">
                <div class="icon scheme"></div>
                <h1>
                    PROJEKTOWANIE I BUDOWA SIECI KOMPUTEROWEJ
                </h1>
                <!--                <p style="padding-top: 1.2rem;">Wykonujemy: sieci komputerowe LAN i WiFi, instalacje elektryczne, monitoring CCTV IP</P>-->
            </div>
            <div class="col what-we-do" style="    animation-delay: 1200ms;">
                <div class="icon settings">
                </div>
                <h1>
                    AUDYTY BEZPIECZEŃSTWA I TESTY PENETRACYJNE
                </h1>
                <!--                <p>Poszukując najlepszych rozwiązań dla naszych Klientów, stale współpracujemy z najlepszymi-->
                <!--                    praktykami</P>-->
            </div>
        </div>
    </div>
</div>
<div class="content-box-white">
    <div class="container" style="height: 250px">
        <div class="hidden-to-animate">
            <h2>OPINIE O NAS</h2>
        </div>
        <div class="row justify-content-center justify-content-lg-between" id="quotes">
            <div class="margin-auto">
                <div class="col">
                    <div class="mySlides animated fadeIn">
                        <img src="web/img/arsanit.png" alt="OutSourcing IT" height="70" width="140">
                        <i class="fas fa-quote-left"></i> Intuicyjna
                        funkcjonalność systemu pozwala na łatwą i bezproblemową obsługę a stała gotowość
                        pracowników firmy Mospan w pełni zapewnia wsparcie <i class="fas fa-quote-right"></i>
                    </div>
                    <div class="mySlides animated fadeIn">
                        <img src="web/img/guhring.jpg" alt="OutSourcing IT" height="70" width="320">
                        <i class="fas fa-quote-left"></i> System w pełni
                        pozwala nam na pełne administrowanie placówkami, tworzenie m.in harmonogramów wizyt,
                        grafików, rozliczeń z NFZ <i class="fas fa-quote-right"></i></div>
                    <div class="mySlides animated fadeIn">
                        <img src="web/img/pkc.png" alt="OutSourcing IT" height="80" width="200">
                        <i class="fas fa-quote-left"></i> Wszystkie usługi
                        wykonywane sa w terminie i z zachowaniem należytej zawodowej staranności <i
                                class="fas fa-quote-right"></i></div>
                    <div class="mySlides animated fadeIn">
                        <img src="web/img/refra.png" alt="OutSourcing IT" height="80" width="220">
                        <i class="fas fa-quote-left"></i> Firma zapewnia
                        profesjonalną obsługę i fachową pomoc. Wszelkie prace wykonywane sa w sposób
                        profesjonalny <i class="fas fa-quote-right"></i></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="content-box-grey-icons">
    <div class="container" style="margin-left: 0px; padding-top: 50px;">
        <div class="row justify-content-center">
            <div class="col-md-4 col-lg-4 col-xs-4 different-img img-mobile-hidden border-shadow" style="    box-shadow: 0px 0px 33px -5px rgba(0, 0, 0, 0.75);"></div>
            <div class="col-md-5 col-lg-5 col-xs-5" style=" padding-left: 40px;">
                <div class="hidden-to-animate">
                    <h2>GDZIE DZIAŁMY</h2>
                </div>
                <div class="under-text" style="margin-bottom: 20px;"> Zapewniamy usługi informatyczne dla firm w następujących miastach:</div>
                <div class="hidden-to-animate-top thumb-text location" style="    animation-delay: 600ms;">
                    <!--                    <div class="thumb">-->
                    <!--                        <i class="far fa-thumbs-up" style="-webkit-font-smoothing: antialiased;"></i>-->
                    <!--                    </div>-->
                    <ul>
                        <li><a href="dabrowagornicza"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Dąbrowa
                                Górnicza</a></li>
                        <li><a href="katowice"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Katowice</a>
                        </li>
                        <li><a href="gliwice"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Gliwice</a>
                        </li>
                        <li><a href="jaworzno"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Jaworzno</a>
                        </li>
                        <li><a href="bedzin"> <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Outsourcing IT Będzin</a></li>
                        <li><i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i> Pozostałe miasta w promieniu do 40km od Dąbrowy
                            Górniczej
                            gdzie
                            znajduje się
                            nasza siedziba.
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="content-box-parallax">
    <div class="container-image">
        <div class="row container-margin">
            <div class="col animation-facts hidden-to-animate-top">
                <div id="odometer1" class="odometer under-text-small-icon">1</div>
                <div class="icon-small">
                    <i class="fas fa-desktop"></i>
                </div>
                </spa>
                <div class="odometer-text"> OBSŁUGIWANYCH STACJI ROBOCZYCH</div>
            </div>
            <div class="col animation-facts hidden-to-animate-top" style="    animation-delay: 500ms; ">
                <div id="odometer2" class="odometer under-text-small-icon">1</div>
                <div class="icon-small">
                    <i class="fas fa-bars"></i>
                </div>
                <div class="odometer-text"> SERWERÓW POD OPIEKĄ</div>
            </div>
            <div class="col animation-facts hidden-to-animate-top" style="    animation-delay: 1000ms;">
                <div id="odometer3" class="odometer under-text-small-icon">1</div>
                <div class="icon-small">
                    <i class="fas fa-user"></i>
                </div>
                <div class="odometer-text" style="text-transform:uppercase;"> ilość wywołanych uśmiechów w biurze gdy padło<br>„O, znowu działa"</div>
            </div>
            <div class="col animation-facts hidden-to-animate-top" style="    animation-delay: 1500ms; ">
                <div id="odometer4" class="odometer under-text-small-icon">1</div>
                <div class="icon-small">
                    <i class="far fa-calendar-alt"></i>
                </div>
                <div class="odometer-text"> LAT DOŚWIADCZENIA NA RYNKU IT</div>
            </div>
        </div>
    </div>
</div>
<div class="content-box-white">
    <div class="container">
        <div class="row row-50 justify-content-center justify-content-lg-between container-margin">
            <div class=" col-md-6 col-lg-6 col-xs-6 hidden-to-animate-top">
                <!--                <h1>OUTSOURCING IT W TWOJEJ FIRMIE</h1>-->
                <!--                <p>Masz już dosyć stresów i zastojów w pracy spowodowanych awaryjnością sprzętu w Twojej firmie?-->
                <!--                    Jeśli tak,<b> to znalazłeś się we właściwym miejscu!</b>-->
                <span style="font-size: 20px; color: rgb(217, 29, 21);"><b>JAK TO WYGLĄDA W PRAKTYCE</b></span>
                <p style="padding-top: 10px; margin-right: 30px">
                    Gdy klient kontaktuje się z nami, ponieważ pojawiła się awaria w jego przedsiębiorstwie najczęściej staramy się usterkę naprawić od razu.
                    Możemy poprowadzić klienta przez cały proces naprawczy telefonicznie lub łączymy się zdalnie z urządzeniem za pomocą aplikacji takich ja
                    np. Team Viewer. Jeśli awaria jest bardziej złożona to w jak najszybszym czasie wysyłamy do klienta naszego specjalistę, który przywraca
                    równowagę w środowisku teleinformatycznym jego firmy. Zazwyczaj wszystko odbywa się tego samego dnia.
                </p>
            </div>
            <div class="col-md-6 col-lg-6 col-xs-6 office-girl img-mobile-hidden border-shadow hidden-to-animate-top">
            </div>
        </div>

    </div>
</div>
<div class="content-box-parallax" id="contact">
    <div class="container-transparent">
        <div class="row row-50 justify-content-center justify-content-lg-between container-margin"
             style="padding-top: 3%;">
            <div class="col-md-12 col-lg-12 col-xs-12">
                <h2 class="hidden-to-animate">SKONTAKTUJ SIĘ Z NAMI</h2>
                <div class="under-text" style="font-size: 1.0rem;">Będzie nam miło porozmawiać z Państwem
                </div>
            </div>
        </div>
        <div class="row container-margin hidden-to-animate-top">
            <div class="col col-left">
                <form class="form" id="contactForm" method="post" novalidate action="send-script.php">
                    <div class="form-row">
                        <label for="field-name">Imię i nazwisko (wymagane)</label>
                        <input type="text" name="name" required id="field-name" data-error="Wypełnij to pole"
                               pattern="[a-zA-ZąĄććęęłŁńŃóÓśŚżŻŹŹ ]+">
                    </div>
                    <div class="form-row">
                        <label for="field-email">Adres email (wymagane)</label>
                        <input type="email" name="email" required id="field-email"
                               data-error="Wpisz poprawny email" pattern="[^@\s]+@[^@\s]+\.[^@\s]+">
                    </div>
                    <div class="form-row">
                        <label for="field-message">Treść wiadomości</label>
                        <textarea name="message" required data-error="Musisz wypełnić pole" id="field-message"
                                  pattern=".+">...</textarea>
                    </div>
                    <div class="form-row">
                        <label class="checkbox-cnt">
                            <input type="checkbox" required data-error="Musisz wypełnić pole" name="regulation">
                            <i class="state" aria-hidden="true"></i>
                            <span>Wyrażam zgodę na używanie przez Trust IT Sp. z.o.o., z siedzibą przy ul. Wróblewskiego 18/103, 93-578 Łódź, telekomunikacyjnych urządzeń końcowych, których jestem użytkownikiem, dla celów marketingu bezpośredniego zgodnie z art. 172 ustawy z dnia 16 lipca 2004 r. Prawo telekomunikacyjne (Dz.U. 2004 nr 171 poz. 1800).*</span>
                        </label>
                    </div>
                    <div class="form-row">
                        <button type="submit" class="submit-btn">Wyślij</button>
                    </div>
                    <div class="g-recaptcha" data-sitekey="6Lf79X8UAAAAAFk3oL6KKWfTyRoZSpwLiPtiSJzm">??</div>
                </form>
            </div class="hidden-to-animate-top">
            <div class="col col-right">
                <p>Dane kontaktowe:</P>
                <div class="thumb-small">
                    <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i>
                </div>
                <p>Adres: <a href="https://www.google.com/maps/place/Parkowa+53,+41-303+Dąbrowa+Górnicza/">Parkowa 53 /2 </a></P>
                <div class="thumb-small">
                    <i class="fa fa-phone" style="-webkit-font-smoothing: antialiased;"></i>
                </div>
                <p>Telefon: <a href="tel:+48 503 757 557">+48 503 757 557</a></P>
                <div class="thumb-small">
                    <i class="fas fa-envelope" style="-webkit-font-smoothing: antialiased;"></i>
                </div>
                <p>Email: <a href="mailto:biuro@vericom.pl">biuro@vericom.pl</a></P>
                <div class="thumb-small">
                    <i class="fas fa-globe-americas" style="-webkit-font-smoothing: antialiased;"></i>
                </div>
                <p>Witryna: <a href="http://vericom.pl">vericom.pl</a></P>
            </div>
        </div>
    </div>
</div>
<div class="content-box-white">
    <div class="container-fluid" style="padding-bottom: 3%">
        <div class="hidden-to-animate" style="    padding-top: 3%;padding-bottom: 1% ">
            <h2>
                ZAUFALI NAM
            </h2>
        </div>
        <div class="row row-50 justify-content-center justify-content-lg-between"
             style=" width: 85%; margin: 0 auto;">
            <!--            <div class="gray-img" style="    display: flex; align-items: center;-->
            <!--    justify-content: center;-->
            <!--    width: 100%;">-->
            <!--                <img src="web/img/arsanit.png" alt="OutSourcing IT" height="90" width="170">-->
            <!--                <img src="web/img/pkc.png" alt="OutSourcing IT" height="80" width="200">-->
            <!--                <img src="web/img/refra.png" alt="OutSourcing IT" height="80" width="220">-->
            <!---->
            <!--                <img src="web/img/ams.png" alt="OutSourcing IT" height="80" width="120">-->
            <!--                <img src="web/img/guhring.jpg" alt="OutSourcing IT" height="60" width="290">-->
            <!--                <img src="web/img/elgum.png" alt="OutSourcing IT" height="70" width="140">-->
            <!--                <img src="web/img/zeusmet.png" alt="OutSourcing IT" height="80" width="180">-->
            <!--            </div>-->

            <div class="owl-carousel" id="carousel" >
                <img src="web/img/arsanit.png" alt="OutSourcing IT" height="90" width="170" >
                <img src="web/img/pkc.png" alt="OutSourcing IT" height="80" width="200" >
                <img src="web/img/refra.png" alt="OutSourcing IT" height="80" width="220" >
                <img src="web/img/guhring.jpg" alt="OutSourcing IT" height="60" width="290" >
                <img src="web/img/ams.png" alt="OutSourcing IT" height="80" width="120" >
                <img src="web/img/elgum.png" alt="OutSourcing IT" height="70" width="140" >
                <img src="web/img/zeusmet.png" alt="OutSourcing IT" height="80" width="180">
            </div>
        </div>
    </div>
</div>
<script>
</script>
