<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>
<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="full-box header-bacground-image2 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!--<div class="content-box-grey">-->
<!--    <div class="container">-->
<!--        <div class="row row-50 justify-content-center justify-content-lg-between container-margin">-->
<!--            <div class="col-md-12 col-lg-12 col-xs-12 animated zoomIn" id="about">-->
<!--                <img src="web/img/stres.jpg" alt="OutSourcing IT" height="350" width="430"-->
<!--                     style="float:left; margin:0.4rem">-->
<!--                <p style="    color: #d91d15;-->
<!--    font-weight: bolder;-->
<!--    letter-spacing: 0.5px;"> Masz już dosyć stresów i zastojów w pracy spowodowanych awaryjnością sprzętu w Twojej-->
<!--                    firmie?-->
<!--                    Jeśli tak, to znalazłeś się we właściwym miejscu!-->
<!--                </p>-->
<!--            </div>-->
<!---->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<div class="content-box-white" id="section1">
    <div class="container">
        <div class="row row-50 justify-content-center justify-content-lg-between container-margin">
            <div class=" col-md-6 col-lg-6 col-xs-6 animated fadeInLeft" id="about">
                <h1>OUTSOURCING IT W TWOJEJ FIRMIE</h1>
                <p>Masz już dosyć stresów i zastojów w pracy spowodowanych awaryjnością sprzętu w Twojej firmie?
                    Jeśli tak,<b> to znalazłeś się we właściwym miejscu!</b>
                    <span> Pomagamy ludziom takim jak Ty od roku XXXX </span>
                </p>
                <img src="web/img/question.jpg" alt="OutSourcing IT" height="140" width="200"
                     style="float:left; margin:0.4rem 0.6rem 0rem 0rem">
                <p>
                <ul class="hidden-to-animate" style="font-weight: bolder;" >
                    <li class="animated fadeIn"><i class="fas fa-question" style="color: rgb(217, 29, 21);margin-right:5px;
                    animation-delay: 2s"></i>Brak internetu
                    </li>
                    <li class="animated fadeIn"><i class="fas fa-question" style="color: rgb(217, 29, 21);
                    margin-right: 5px;"></i>Migający monitor
                    </li>
                    <li class="animated fadeIn"><i class="fas fa-question" style="color: rgb(217, 29,
                    21); margin-right: 5px;"></i>Wyłączający się komputer
                    </li>
                    <li class="animated fadeIn"><i class="fas fa-question" style="color: rgb(217, 29,
                    21); margin-right: 5px;"></i>Brak możliwości połączenia się z serwerem
                    </li>
                    <li  class="animated fadeIn"><i class="fas fa-question" style="color: rgb(217, 29, 21);
                    margin-right: 5px;">
                        </i>Nie działające kamery
                    </li>
                    <li class="animated fadeIn"><i class="fas fa-question" style="color: rgb(217, 29, 21);
                    margin-right: 5px;"></i>Notoryczne błędy
                    </li>
                </ul>
                <p style="padding-top: 10px;"><b>To tylko przykładowe sytuacje, które zdarzają się w przedsiębiorstwach każdego dnia.</b>
                Naprawa awarii pochłania zawsze dużą
                ilość czasu, angażuje wiele osób oraz wywołuje nieraz niemałe zamieszanie. A jak wiemy czas to
                pieniądz.

                Dobrze być na to przygotowanym i powierzyć opiekę nad „złośliwością rzeczy martwych” specjalistom z
                wieloletnim doświadczeniem. Jesteśmy tu dla Ciebie.
                </p>
            </div>
            <div class="col-md-6 col-lg-6 col-xs-6">
                <div>
                    <div id="example-1" style="margin-top: 10%;">
                        <div class="bar cssProgress">
                            <div class="progress1">
                                <p>Zadowolonych Klientów</p>
                                <div class="bar cssProgress-bar" data-percent="98" style="width: 75%;">
                                    <span class="cssProgress-label first75">98%</span>
                                </div>
                            </div>
                        </div>
                        <div class="cssProgress">
                            <div class="progress1">
                                <p>Dotrzymany czas reakcji</p>
                                <div class="cssProgress-bar" data-percent="94" style="width: 65%;">
                                    <span class="cssProgress-label">65%</span>
                                </div>
                            </div>
                        </div>
                        <div class="cssProgress">
                            <div class="progress1">
                                <p>Wdrożonych sytemów w wyznaczonym terminie</p>
                                <div class="cssProgress-bar" data-percent="100" style="width: 55%;">
                                    <span class="cssProgress-label">100%</span>
                                </div>
                            </div>
                        </div>
                        <div class="cssProgress">
                            <div class="progress1">
                                <p>Realizacja zamówień w terminie</p>
                                <div class="cssProgress-bar" data-percent="95" style="width: 45%;">
                                    <span class="cssProgress-label">95%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="content-box-grey">
    <div class="container">
        <div class="row row-50 justify-content-center justify-content-lg-between container-margin">
            <div class="col-md-12 col-lg-12 col-xs-12">
                <div class="hidden-to-animate">
                    <h2>
                        CZYM SIĘ ZAJMUJEMY
                    </h2>
                </div>
                <div class="under-text"> Sprawdź w jakich dziedzinach IT specjalizujemy się</div>
            </div>
            <div class="col what-we-do">
                <div class="icon service">
                </div>
                <h1>
                    <a href=""> OPIEKA INFORMATYCZNA FIRM </a>
                </h1>
                <p style="padding-top: 1.2rem;">Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem
                    IT, </P>
            </div>
            <div class="col what-we-do" style="    animation-delay: 400ms;">
                <div class="icon linechart"></div>
                <h1>
                    <a href="">SYSTEMY IT NA ZAMÓWIENIE</a>
                </h1>
                <p style="padding-top: 1.2rem;">Specjalizujemy się w projektowaniu systemów informatycznych</P>
            </div>
            <div class="col what-we-do" style="    animation-delay: 800ms;">
                <div class="icon scheme"></div>
                <h1>
                    <a href=""> PROJEKTOWANIE I BUDOWA SIECI KOMPUTEROWEJ</a>
                </h1>
                <p style="padding-top: 1.2rem;">Wykonujemy: sieci komputerowe LAN i WiFi, instalacje elektryczne, monitoring CCTV IP</P>
            </div>
            <div class="col what-we-do" style="    animation-delay: 1200ms;">
                <div class="icon settings">
                </div>
                <h1>
                    <a href=""> AUDYTY BEZPIECZEŃSTWA I TESTY PENETRACYJNE </a>
                </h1>
                <p>Poszukując najlepszych rozwiązań dla naszych Klientów, stale współpracujemy z najlepszymi
                    praktykami</P>
            </div>
        </div>
    </div>
</div>
<div class="content-box-white">
    <div class="container-fluid">
        <div class="hidden-to-animate" style="    padding-top: 3%;">
            <h2>
                REFERENCJE
            </h2>
        </div>
        <div class="under-text"> Sprawdź wybrane opinie na temat naszej pracy</div>
        <div class="row row-50 justify-content-center justify-content-lg-between"
             style=" width: 95%; margin: 0 auto;">
            <div class="col-lg-3 col-md-6">
                <div class=" parent" onclick="">
                    <div class="child bg-one" id="portfolio">
                        <a href="#">Los Angeles</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class=" parent" onclick="">
                    <div class="child bg-two" id="portfolio">
                        <a href="#">London</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 ">
                <div class=" parent" onclick="">
                    <div class="child bg-three" id="portfolio">
                        <a href="#">New York</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 ">
                <div class=" parent" onclick="">
                    <div class="child bg-four" id="portfolio">
                        <a href="#">Hollywood</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="content-box-grey-icons">
    <div class="container" style="margin-left: 0px;">
        <div class="row">
            <div class="col different-img"></div>
            <div class="col" style=" padding-left: 40px;   padding-top: 3%;  padding-bottom:  6%;   ">
                <div class="hidden-to-animate">
                    <h2>CO NAS WYRÓŻNIA</h2>
                </div>
                <div class="under-text"> Nasze atuty - Oferowane korzyści</div>
                <div class="hidden-to-animate-top thumb-text" style="    animation-delay: 600ms;">
                    <div class="thumb">
                        <i class="far fa-thumbs-up" style="-webkit-font-smoothing: antialiased;"></i>
                    </div>
                    <h4>21 letnie doświadczenie! </h4>
                    <div class="diffrent-text">Mamy 21 letnie doświadczenie w kompleksowej obsłudze
                        informatycznej firm
                    </div>
                </div>
                <div class="hidden-to-animate-top thumb-text" style="    animation-delay: 900ms;">
                    <div class="thumb">
                        <i class="far fa-thumbs-up" style="-webkit-font-smoothing: antialiased;"></i>
                    </div>
                    <h4>Jakość potwierdzona zaufaniem</h4>
                    <div class="diffrent-text">Zaufało nam już kilkudziesięciu klientów z wielu branż</div>
                </div>
                <div class="hidden-to-animate-top thumb-text" style="    animation-delay: 1200ms;">
                    <div class="thumb">
                        <i class="far fa-thumbs-up" style="-webkit-font-smoothing: antialiased;"></i>
                    </div>
                    <h4>Szybki czas reakcji</h4>
                    <div class="diffrent-text">Oferujemy najwyższe standardy obsługi i błyskawiczny czas reakcji
                        na zgłoszenia
                    </div>
                </div>
                <div class="hidden-to-animate-top thumb-text" style="    animation-delay: 1500ms;">
                    <div class="thumb">
                        <i class="far fa-thumbs-up" style="-webkit-font-smoothing: antialiased;"></i>
                    </div>
                    <h4>Lojalność i profesjonalizm</h4>
                    <div class="diffrent-text">Mogą być Państwo pewni, że nasza kadra to osoby doświadczone z
                        wieloletnim stażem
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="content-box-parallax">
    <div class="container-image">
        <h2 class="hidden-to-animate">KILKA FAKTÓW O NAS</h2>
        <div class="under-text">VeriCom w liczbach</div>
        <div class="row container-margin">
            <div class="col animation-facts hidden-to-animate-top">
                <div id="odometer1" class="odometer under-text-small-icon">1</div>
                <div class="icon-small">
                    <i class="fas fa-desktop"></i>
                </div>
                </spa>
                <div class="odometer-text"> OBSŁUGIWANYCH STACJI ROBOCZYCH</div>
            </div>
            <div class="col animation-facts hidden-to-animate-top" style="    animation-delay: 500ms; ">
                <div id="odometer2" class="odometer under-text-small-icon">1</div>
                <div class="icon-small">
                    <i class="fas fa-bars"></i>
                </div>
                <div class="odometer-text"> SERWERÓW POD OPIEKĄ</div>
            </div>
            <div class="col animation-facts hidden-to-animate-top" style="    animation-delay: 1000ms;">
                <div id="odometer3" class="odometer under-text-small-icon">1</div>
                <div class="icon-small">
                    <i class="fas fa-user"></i>
                </div>
                <div class="odometer-text"> OBSŁUGIWANYCH PRZEDSIĘBIORSTW</div>
            </div>
            <div class="col animation-facts hidden-to-animate-top" style="    animation-delay: 1500ms; ">
                <div id="odometer4" class="odometer under-text-small-icon">1</div>
                <div class="icon-small">
                    <i class="far fa-calendar-alt"></i>
                </div>
                <div class="odometer-text"> LAT DOŚWIADCZENIA NA RYNKU IT</div>
            </div>
        </div>
    </div>
</div>
<div class="content-box-white">
    <div class="container">
        <div class="hidden-to-animate">
            <h2>Opinie o Nas</h2>
        </div>
        <div class="under-text">Co nasi Klienci o nas mówią</div>

        <div class="row justify-content-center justify-content-lg-between" id="quotes">
            <div class="margin-auto">
                <div class="col">
                    <div class="mySlides animated fadeIn"><i class="fas fa-quote-left"></i> Intuicyjna
                        funkcjonalność systemu pozwala na łatwą i bezproblemową obsługę a stała gotowość
                        pracowników firmy Mospan w pełni zapewnia wsparcie <i class="fas fa-quote-right"></i>
                    </div>
                    <div class="mySlides animated fadeIn"><i class="fas fa-quote-left"></i> System w pełni
                        pozwala nam na pełne administrowanie placówkami, tworzenie m.in harmonogramów wizyt,
                        grafików, rozliczeń z NFZ <i class="fas fa-quote-right"></i></div>
                    <div class="mySlides animated fadeIn"><i class="fas fa-quote-left"></i> wszystkie usługi
                        wykonywane sa w terminie i z zachowaniem należytej zawodowej staranności <i
                                class="fas fa-quote-right"></i></div>
                    <div class="mySlides animated fadeIn"><i class="fas fa-quote-left"></i> Firma zapewnia
                        profesjonalną obsługę i fachową pomoc. Wszelkie prace wykonywane sa w sposób
                        profesjonalny <i class="fas fa-quote-right"></i></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="content-box-parallax" id="contact">
    <div class="container-transparent">
        <div class="row row-50 justify-content-center justify-content-lg-between container-margin"
             style="padding-top: 3%;">
            <div class="col-md-12 col-lg-12 col-xs-12">
                <h2 class="hidden-to-animate">SKONTAKTUJ SIĘ Z NAMI</h2>
                <div class="under-text" style="  font-size: 1.0rem;">Będzie nam miło porozmawiać z Państwem
                </div>
            </div>
        </div>
        <div class="row container-margin hidden-to-animate-top">
            <div class="col col-left">
                <form class="form" id="contactForm" method="post" novalidate action="send-script.php">
                    <div class="form-row">
                        <label for="field-name">Imię i nazwisko (wymagane)</label>
                        <input type="text" name="name" required id="field-name" data-error="Wypełnij to pole"
                               pattern="[a-zA-ZąĄććęęłŁńŃóÓśŚżŻŹŹ ]+">
                    </div>
                    <div class="form-row">
                        <label for="field-email">Adres email (wymagane)</label>
                        <input type="email" name="email" required id="field-email"
                               data-error="Wpisz poprawny email" pattern="[^@\s]+@[^@\s]+\.[^@\s]+">
                    </div>
                    <div class="form-row">
                        <label for="field-message">Treść wiadomości</label>
                        <textarea name="message" required data-error="Musisz wypełnić pole" id="field-message"
                                  pattern=".+">...</textarea>
                    </div>
                    <div class="form-row">
                        <label class="checkbox-cnt">
                            <input type="checkbox" required data-error="Musisz wypełnić pole" name="regulation">
                            <i class="state" aria-hidden="true"></i>
                            <span>Wyrażam zgodę na używanie przez Trust IT Sp. z.o.o., z siedzibą przy ul. Wróblewskiego 18/103, 93-578 Łódź, telekomunikacyjnych urządzeń końcowych, których jestem użytkownikiem, dla celów marketingu bezpośredniego zgodnie z art. 172 ustawy z dnia 16 lipca 2004 r. Prawo telekomunikacyjne (Dz.U. 2004 nr 171 poz. 1800).*</span>
                        </label>
                    </div>
                    <div class="form-row">
                        <button type="submit" class="submit-btn">Wyślij</button>
                    </div>
                    <div class="g-recaptcha" data-sitekey="6Lf79X8UAAAAAFk3oL6KKWfTyRoZSpwLiPtiSJzm">??</div>
                </form>
            </div class="hidden-to-animate-top">
            <div class="col col-right">
                <p>Dane kontaktowe:</P>
                <div class="thumb-small">
                    <i class="fas fa-map-marker-alt" style="-webkit-font-smoothing: antialiased;"></i>
                </div>
                <p>Adres: Parkowa 53 /2</P>
                <div class="thumb-small">
                    <i class="fa fa-phone" style="-webkit-font-smoothing: antialiased;"></i>
                </div>
                <p>Telefon: +48 503 757 557</P>
                <div class="thumb-small">
                    <i class="fas fa-envelope" style="-webkit-font-smoothing: antialiased;"></i>
                </div>
                <p>Email: biuro@vericom.pl</P>
                <div class="thumb-small">
                    <i class="fas fa-globe-americas" style="-webkit-font-smoothing: antialiased;"></i>
                </div>
                <p>Witryna: http://vericom.pl</P>
            </div>
        </div>
    </div>
</div>
