<style>.tick-ul ul {
        list-style: none;
    }

    .tick-ul ul li:before {
        color: red;
        font-weight: bolder;
        content: '✓';
        padding-right: 5px;
    }</style>

<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>

<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="full-box header-bacground-image2 animated fadeInSlider headers">
        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="content-box-white" id="section1">
    <div class="container" style="    min-width: 70%;">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-8 animated zoomIn tick-ul" id="about" style="text-align: justify;">
                <h1> Katowice </h1>
            <p>
                Większość firm obecnie swoją codzienną pracę opiera na nowoczesnym sprzęcie komputerowym. Jednak trzeba się liczyć z tym, że nadal są to jednak urządzenia, które mogą ulegać awarii. Dlatego warto zadbać między innymi o stworzenie takich warunków, w których będzie można mieć stałą kontrole nad tymi urządzeniami i ich technicznym stanem. Jeśli firma nie chce tworzyć kompleksowo działu informatycznego warto będzie wykorzystać usługi informatyczne dla firm w Katowicach świadczone przez zewnętrzne podmioty.
            </p>
                <h2>Profesjonalny outsourcing IT w Katowicach</h2>
                <p>
                    Obecnie możemy liczyć na profesjonalny outsourcing IT w Katowicach, który będzie realizowany przez doświadczone firmy, które mają odpowiednie w tym zakresie przygotowanie i są w stanie kompleksowo zająć się sprzętem komputerowym jaki w firmie funkcjonuje. Obsługa informatyczna dla firm przez zewnętrzne podmioty to bardzo duża wygoda, ponieważ przy nawiązaniu stałej współpracy można liczyć na pomoc takich firm, a jednocześnie nie będzie obaw o wysokie koszty, które pojawiłyby się, gdyby ktoś w tym temacie została zatrudniony w firmie na etat.
                </p>
               <?php include("city-common.phtml"); ?>
            </div>
            <div class="col-4">
                <div class="text-box">
                    <h3> Adres </h3>
                    <p>
                        VERICOM <br> ul. Parkowa 53 /2 <br> 41-303 Dąbrowa Górnicza
                    </p>
                    <p>
                        NIP: 6292075389<br> REGON: 241660764
                    </p>
                </div>
                <div class="text-box">
                    <h3> Telefon i fax </h3>
                    <p>
                        +48 502 481 334</br>
                        +48 503 757 557
                    </p>
                </div>
                <div class="text-box">
                    <h3> E-mail </h3>
                    <p>
                        biuro@vericom.pl
                    </p>
                </div>
                <div class="text-box">
                    <h3> Facebook </h3>
                    <p>
                        facebook.com/vericom
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
