<style>
    .tick-ul ul {
        list-style: none;
    }

    .tick-ul ul li:before {
        color: red;
        font-weight: bolder;
        content: '✓';
        padding-right: 5px;
    }
    li {
        margin-bottom: 10px;
    }
    .animation-box {
        position: absolute;
        top: 166px;
        align-items: center;
    }
    .full-box {
        min-width: auto;
        min-height: 500px;
    }
    h1 {
        font-family: 'Roboto Condensed', sans-serif;
        font-size: 2rem;
        text-align: left;
        color: rgb(217, 29, 21);
        margin-bottom: 1.5rem;
        letter-spacing: 1px;
    }
    h2 {
        font-family: 'Roboto Condensed', sans-serif;
        font-size: 2rem;
        text-align: left;
        color: rgb(217, 29, 21);
        margin-bottom: 1.5rem;
        letter-spacing: 1px;
    }
</style>

<button id="back-to-top" title="Go to top"><i class="fas fa-angle-up"></i></button>

<header class=" dotted">
    <div class="full-box header-bacground-image1 animated fadeInSlider headers">
        <div class="animation-box">
            <div class="animated fadeInLeft animation-text-first">
                <div class="animated fadeIn">OUTSOURCING IT KATOWICE
                </div>
            </div>
            <div style="overflow-x: hidden;">
                <div class="animated fadeInRight animation-text-second">
                    <div class="animated fadeIn">
                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla
                        użytkowników (Helpdesk) oraz administrowania siecią
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--    <div class="full-box header-bacground-image2 animated fadeInSlider headers">-->
<!--        <button class="arrow arrow-left" onclick="plusDivs(-1)">&#10094;</button>-->
<!--        <button class="arrow arrow-right" onclick="plusDivs(1)">&#10095;</button>-->
<!--        <div class="animation-box">-->
<!--            <div class="animated fadeInLeft animation-text-first">-->
<!--                <div class="animated fadeIn">OPIEKA INFORMATYCZNA FIRM-->
<!--                </div>-->
<!--            </div>-->
<!--            <div style="overflow-x: hidden;">-->
<!--                <div class="animated fadeInRight animation-text-second">-->
<!--                    <div class="animated fadeIn">-->
<!--                        Zapewniamy kompleksowe wsparcie w zakresie opieki nad sprzętem IT, bieżącej pomocy dla-->
<!--                        użytkowników (Helpdesk) oraz administrowania siecią-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
</header>

<div class="content-box-white" id="section1">
    <div class="container" style="    min-width: 70%;">
        <div class="row row-50 justify-content-center justify-content-lg-between container-mrgin about2">
            <div class="col-7 animated zoomIn tick-ul" id="about" style="text-align: justify;">
                <h1> Katowice </h1>
                <p>
                    Większość firm obecnie swoją codzienną pracę opiera na nowoczesnym sprzęcie komputerowym. Jednak trzeba się liczyć z tym, że nadal są to jednak urządzenia, które mogą ulegać awarii. Dlatego warto zadbać między innymi o stworzenie takich warunków, w których będzie można mieć stałą kontrole nad tymi urządzeniami i ich technicznym stanem. Jeśli firma nie chce tworzyć kompleksowo działu informatycznego warto będzie wykorzystać usługi informatyczne dla firm w Katowicach świadczone przez zewnętrzne podmioty.
                </p>
                <h2>Profesjonalny outsourcing IT w Katowicach</h2>
                <p>
                    Obecnie możemy liczyć na profesjonalny outsourcing IT w Katowicach, który będzie realizowany przez doświadczone firmy, które mają odpowiednie w tym zakresie przygotowanie i są w stanie kompleksowo zająć się sprzętem komputerowym jaki w firmie funkcjonuje. Obsługa informatyczna dla firm przez zewnętrzne podmioty to bardzo duża wygoda, ponieważ przy nawiązaniu stałej współpracy można liczyć na pomoc takich firm, a jednocześnie nie będzie obaw o wysokie koszty, które pojawiłyby się, gdyby ktoś w tym temacie została zatrudniony w firmie na etat.
                </p>
                <?php include("city-common.phtml"); ?>
            </div>
            <div class="col-4 city border-shadow animated zoomIn" style="box-shadow: 0px 0px 35px -7px rgba(0, 0, 0, 0.75);">
            </div>
        </div>
    </div>
</div>
