<div class="full-box-menu" id="full-box-menu">
    <div class="container-menu">
        <div class="hamburger" id="hamburger" onclick="myHamburger()">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
        </div>
        <div class="logobox">
            <div class="logo" id="logo">
            </div>
        </div>
        <div class="menu-normal" id="top-menu">
            <ul class="">
               <?php nav_menu('nav_menu'); ?>
            </ul>
        </div>
    </div>
    <div id="navigation" class="menu menu-link">
        <ul class="topnav" id="myTopnav">
            <?php nav_menu('nav_menu'); ?>
        </ul>
    </div>
</div>
