<div class="full-box-menu" id="full-box-menu">
    <div class="container-menu">
        <div class="hamburger" id="hamburger" onclick="myHamburger()">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
        </div>
        <div class="logobox">
            <div class="logo" id="logo">
            </div>
        </div>
        <div class="menu-normal" id="top-menu">
            <ul class="">
                <ul><?php nav_menu('nav_menu'); ?></ul>
            </ul>
        </div>
    </div>
    <div id="navigation" class="menu menu-link">
        <ul class="topnav" id="myTopnav">
            <li><a href="application/views/home.phtml">STRONA GŁÓWNA</a></li>
            <li><a href="/">ŚWIADCZONE USŁUGI</a></li>
            <li><a href="/">OBSŁUGIWANE MIASTA</a></li>
            <li><a href="/">Pomoc zdalna</a></li>
            <li><a href="application/views/about.phtml">O Nas</a></li>
            <li><a href="/">Kontakt</a></li>
        </ul>
    </div>
</div>
