<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VeriCom OutSourcing IT</title>
    <link href="web/css/reset.css" rel="stylesheet" type="text/css" media="all">
    <link href="web/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
    <link href="web/css/style.css" rel="stylesheet" type="text/css" media="all">
    <link href="web/css/contact.css" rel="stylesheet" type="text/css" media="all">
    <link href="web/css/animate.css" rel="stylesheet" type="text/css" media="all">
    <link href="web/css/odometer.css" rel="stylesheet" type="text/css" media="all">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body onload="init()" style="overflow-x: hidden ">
<main>
    <section class="container-fluid">
        <?php include 'views/menu.phtml'; ?>
        <?php page_content(); ?>
        <?php include 'views/footer.phtml'; ?>
    </section>
</main>
<script src='https://www.google.com/recaptcha/api.js'></script>
<script type="text/javascript" src="web/js/bootstrap.min.js"></script>
<script type="text/javascript" src="web/js/outdatedbrowser.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-migrate-3.0.1.js"></script>
<script type="text/javascript" src="web/js/scroll.js"></script>
<script type="text/javascript" src="web/js/animate.js"></script>
<script type="text/javascript" src="web/js/scripts.js"></script>
</body>
</html>
